# Created by: Laurent Cimon <laurent@nilio.ca>
# $FreeBSD$

PORTNAME=	cx
PORTVERSION=	0.2
PORTREVISION=	1
CATEGORIES=	sysutils
MASTER_SITES=	https://nilio.ca/cx/

MAINTAINER=	Laurent Cimon <laurent@nilio.ca>
COMMENT=	A directory history management utility

LICENSE=	BSD-2-Clause
LICENSE_FILE=	${WRKSRC}/LICENSE

LIB_DEPENDS=	libsqlite3.so:databases/sqlite3

USES=		sqlite tar:xz

.include <bsd.port.mk>
